# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Setup
title:               Alejandro J Rico
tagline:             'Technical thoughts, mostly'
description:         'Technical projects and notes by Alejandro J Rico'
url:                 http://aljrico.github.io
baseurl:             /
paginate:            5
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Pages
pages:
  Archive: '/archive'
  About: '/about'
  Tags: '/tags'

  # Menu
menu:
- {name: 'About Me', path: 'menu', url: '../about'}
- {name: 'My CV', path: 'menu', url: '../cv'}
- {name: 'Archive', path: 'menu', url: '../archive'}


# About/contact
author:
  name:              'Alejandro Jimenez Rico'
  url:               http://aljrico.github.io

github:
  repo:              https://github.com/aljrico/aljrico.github.io

sass:
  sass_dir: _sass
  style: :compressed


 # Localization Strings
 str_continue_reading: "Continue reading..."



#### Theme customization -----------------------------

# Color for top bar, links, etc
highlight_color: '#4a6978'

# Profile links on the left sidebar, leave blank to ignore
social:
  github: aljrico
  #bitbucket: philipj
  #hacker_news: swanson
  #stackexchange: 348619
  #stackoverflow: 348619
  #twitter: _swanson
  #facebook: zuck
  #tumblr: animalygifs
  linkedin: aljrico
  #gplus: 110552447039675960964
  #gravatar: 86e6ff8f75f9daef42d53b7f8002fd95
  #flickr: johndoe

# "Hi, I'm _______"
name: Alejandro Jiménez Rico
email: aljrico@gmail.com
tagline: "A man got to have a code"

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-117527884-1

# Toggle "Postings are my own" disclaimer in footer
show_disclaimer: true

# Toggle link/icon to view atom feed (/atom.xml) in sidebar
show_atom_feed: true

