# Dependencies
highlighter:         pygments

# Setup
title:               Alejandro J Rico
tagline:             'Notes, thoughts and personal projects'
description:         'Notes, thoughts and peronsal projects of Alejandro Jimenez Rico'
url:                 http://aljrico.github.io
baseurl:             /
paginate:            5
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Pages
pages:
  Blog Archive: '/blog'
  About: '/about'
  Tags: '/tags'

# About/contact
author:
  name:              'Alejandro Jimenez Rico'
  url:               http://aljrico.github.io

github:
  repo:              http://github.com/aljrico/aljrico.github.io

sass:
  sass_dir: _sass
  style: :compressed

# Theme
theme:

 # Localization Strings
 str_continue_reading: "Continue reading..."
