# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Setup
title:               Alejandro J Rico
tagline:             'Technical thoughts, mostly'
description:         'Technical projects and notes by Alejandro J Rico'
url:                 http://aljrico.github.io
baseurl:             /
paginate:            5
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
