---
output:
  md_document: default
  html_document: default
---
---
layout: post
title: Optimizing drugs distribution in a developing country
categories:
- blog
output:
  md_document:
    variant: markdown_github


In this post I will try exemplify how **Data Science** can be of great help when trying to address real-world problems. Today we'll optimize drugs distribution of some uknown place, just looking at the raw data provided by the medical services in place.

Even though we are not trying to usurpe the role of Physicians in their field, we'll try to show how useful can be the application of Data Science techniques in order to *cooperate* with Medical Services. Especially in scenarios of scarcity or emergency, where medical specialists are having a hard time dealing with huge loads of people in need of their help. In this extreme situations, decision-making processes are more critical than ever.



# Fetching Data

First of all, let's grab all data we can put our hands on. For the sake of the example, I came with three different .csv files with medical records or general information. Disorganized, untidy, messy and imperfect.


